### PR TITLE
[TEST] Bma2x2 bringup

### PR DESCRIPTION
**Pull request by danielgusvt**
We have to test this one

### CODE REVIEW

**Comment by bartcubbins** [comment]
https://github.com/bartcubbins/kernel_kanuti/pull/13/commits/a6fa3629c1e83047662aa525a56ee7c5374b87f1
better comment this instead of removing or remove this ifdef from the whole driver

**Comment by bartcubbins** [comment]
https://github.com/bartcubbins/kernel_kanuti/pull/13/commits/9151b7f5cb53e5a101f1b91bef2f0d6ed59ff7eb
already enabled;)

**Comment by danielgusvt** [comment]
@bartcubbins I must be blind xd

**Comment by danielgusvt** [comment]
also what do you mean by removing ifdef?

**Comment by bartcubbins** [comment]
string no 18, 1271, 1879, etc...

**Comment by danielgusvt** [comment]
Oh I understood what you meant, but please have a better read at the commit message
_It is wrong to have this enabled by default since we are provided by a
config to enable/disable this_
https://github.com/RiseOS/kernel_sony_msm8939/blob/fixes/drivers/input/misc/Kconfig#L826-L832
https://github.com/RiseOS/kernel_sony_msm8939/blob/fixes/drivers/input/misc/Makefile#L86-L88
I do not plan to kill this functionality, I just want to disable it by not enabling by default; since we can still enable it properly with a config, which was wrong because BMA2X2_ENABLE_INT2 will be always enabled regardless if we use or not use the CONFIG_BOSCH_BMA2X2_ENABLE_INT2 config

**Comment by bartcubbins** [comment]
then just comment this define instead of removing
https://github.com/bartcubbins/kernel_kanuti/commit/a6fa3629c1e83047662aa525a56ee7c5374b87f1#diff-221e5f18f1f37ddf5a54991eb9774220L18

**Comment by danielgusvt** [comment]
Sure, I will do it

**Comment by danielgusvt** [comment]
@bartcubbins pull request updated:)

**Comment by bartcubbins** [comment]
good job, ty!:)

**Pull request merged**
